version: "3.9"  # optional since v1.27.0
services:
  backend:
    build: Server/flask_backend/.
    ports: 
        - "8000:8000"
  frontend:
    build: Client/svelte-app/.
    links:
        - backend
    ports: 
        - "5000:5000"